import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
test('complete project lifecycle survives reload and exports an interactive prototype', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Hello, Designer.' })).toBeVisible();
  await page.getByRole('link', { name: 'Create a project', exact: true }).click();
  await page.getByLabel('Your idea', { exact: true }).fill('Food delivery for university students');
  await page.getByLabel('Who is it for?').fill('Students');
  await page.getByRole('button', { name: 'Create design', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'CampusEats', exact: true })).toBeVisible();
  await page.getByLabel('Project name', { exact: true }).fill('Campus Kitchen');
  await page.getByRole('button', { name: 'Save brief', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Campus Kitchen', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Studio', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Good food. Good mood.', exact: true }).click();
  await page.getByLabel('Label / content').fill('Fresh food for your day');
  await page.getByRole('button', { name: 'Save element', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Edit Fresh food for your day', exact: true })).toBeVisible();
  await page.getByLabel('Design instruction').fill('Dark theme');
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(page.locator('.phone')).toHaveCSS('background-color', 'rgb(21, 19, 28)');
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  await page.locator('.phone').getByRole('button', { name: /Fresh bowls/ }).click();
  await expect(page.locator('.phone').getByRole('heading', { name: 'Fresh bowls' })).toBeVisible();
  await page.locator('.phone').getByRole('button', { name: 'Continue to checkout' }).click();
  await page.locator('.phone').getByLabel('Your name').fill('Alex');
  await page.locator('.phone').getByRole('button', { name: 'Place order' }).click();
  await expect(page.locator('.phone').getByRole('heading', { name: 'You’re all set.' })).toBeVisible();
  await page.getByRole('link', { name: 'Review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A solid foundation.' })).toBeVisible();
  await page.getByRole('link', { name: 'History', exact: true }).click();
  await page.locator('.history-item').first().getByRole('button', { name: 'Restore' }).click();
  await page.getByRole('link', { name: 'Studio', exact: true }).click();
  await expect(page.locator('.phone')).toHaveCSS('background-color', 'rgb(246, 244, 252)');
  await page.screenshot({ path: `artifacts/studio-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: 'Export', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export .html', exact: true }).click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toBe('designflow-prototype.html');
  await download.saveAs(`artifacts/prototype-${testInfo.project.name}.html`);
  const prototype = await page.context().newPage(); await prototype.goto(pathToFileURL(resolve(`artifacts/prototype-${testInfo.project.name}.html`)).href);
  await expect(prototype.getByRole('heading', { name: 'Fresh food for your day' })).toBeVisible();
  await prototype.getByRole('button', { name: /Fresh bowls/ }).click();
  await expect(prototype.getByRole('heading', { name: 'Fresh bowls' })).toBeVisible(); await prototype.close();
  await page.goto('/#home');
  await expect(page.getByRole('heading', { name: 'Campus Kitchen' })).toBeVisible();
  await page.screenshot({ path: `artifacts/home-${testInfo.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('local mode shows honest errors, rejects invalid imports, and filters favorites', async ({ page }) => {
  await page.goto('/#templates');
  await page.getByRole('button', { name: 'Use template' }).first().click();
  await page.getByRole('link', { name: 'Studio', exact: true }).click();
  await page.getByLabel('Design instruction').fill('Create a detailed banking dashboard');
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(page.locator('#toast')).toContainText('Connect an AI server');
  await page.goto('/#projects');
  await page.getByRole('button', { name: 'Favorites', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No projects here yet' })).toBeVisible();
  await page.getByRole('button', { name: 'Favorites', exact: true }).click();
  await page.getByRole('button', { name: 'Favorite CampusEats', exact: true }).click();
  await page.getByRole('button', { name: 'Favorites', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'CampusEats' })).toBeVisible();
  const chooser = page.waitForEvent('filechooser'); await page.getByRole('button', { name: 'Import backup', exact: true }).click();
  await (await chooser).setFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"format":"invalid"}') });
  await expect(page.locator('#toast')).toHaveClass(/visible/);
  await expect(page.getByRole('heading', { name: 'CampusEats' })).toBeVisible();
});
